# Generated by Django 3.0.5 on 2020-08-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_say', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(default=0)),
                ('product_price_starting', models.IntegerField(default=0)),
                ('product_head1', models.CharField(max_length=1500, null=True)),
                ('product_head2', models.CharField(max_length=1500, null=True)),
                ('product_head3', models.CharField(max_length=1500, null=True)),
                ('product_head4', models.CharField(max_length=1500, null=True)),
                ('product_head5', models.CharField(max_length=1500, null=True)),
                ('product_desc', models.CharField(max_length=1500)),
                ('product_desc1', models.CharField(max_length=1500, null=True)),
                ('product_desc2', models.CharField(max_length=1500, null=True)),
                ('product_desc3', models.CharField(max_length=1500, null=True)),
                ('product_desc4', models.CharField(max_length=1500, null=True)),
                ('product_desc5', models.CharField(max_length=1500, null=True)),
                ('product_date', models.DateField(verbose_name='date published')),
                ('product_img1', models.ImageField(upload_to='shop/images')),
                ('product_img2', models.ImageField(upload_to='shop/images')),
                ('product_img3', models.ImageField(null=True, upload_to='shop/images')),
                ('product_img4', models.ImageField(null=True, upload_to='shop/images')),
            ],
        ),
    ]
