# Generated by Django 3.0.5 on 2020-08-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_name', models.CharField(max_length=50)),
                ('ad_img1', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
