# Generated by Django 3.0.5 on 2020-08-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='ad_img2',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='ads',
            name='ad_img3',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
    ]
