# Generated by Django 3.0.5 on 2020-08-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200812_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_desc3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_desc4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_desc5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_head3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_head4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_head5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_img3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_img4',
        ),
    ]
