# Generated by Django 3.0.5 on 2020-08-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200813_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='ad_img2',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='ad_img3',
        ),
    ]
