# Generated by Django 3.0.5 on 2020-08-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200815_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_products', models.CharField(max_length=10000)),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=700)),
                ('city', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('zip_code', models.IntegerField(max_length=8)),
                ('mail', models.CharField(max_length=200)),
                ('phone1', models.IntegerField(max_length=12)),
                ('phone2', models.IntegerField(max_length=12)),
            ],
        ),
    ]
