# Generated by Django 3.0.5 on 2020-08-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided_id', models.IntegerField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
            ],
        ),
    ]
