# Generated by Django 3.0.5 on 2020-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_update',
            name='track_desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
