# Generated by Django 3.0.5 on 2020-08-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_update_track_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track_Update',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('track_desc', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided_id', models.IntegerField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Order_Update',
        ),
    ]
