# Generated by Django 3.0.5 on 2020-08-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200821_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track_Update',
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
