# Generated by Django 3.0.5 on 2020-08-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200821_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
