# Generated by Django 3.0.5 on 2020-08-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200823_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='trackdesc1',
            field=models.CharField(default='Order Has Been Placed', max_length=500),
        ),
        migrations.AddField(
            model_name='orders',
            name='trackdesc2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='trackdesc3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='trackdesc4',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
