# Generated by Django 3.0.5 on 2020-08-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200823_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='trackdesc1',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='trackdesc2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='trackdesc3',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='trackdesc4',
        ),
    ]
