# Generated by Django 3.0.5 on 2020-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200824_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mv_product_kh1',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mv_product_kh2',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mv_product_kh3',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mv_product_khd1',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mv_product_khd2',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mv_product_khd3',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mv_product_khd4',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mv_product_khd5',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mv_product_khd6',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mv_product_khd7',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mv_product_khd8',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mv_product_khd9',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
