# Generated by Django 3.0.5 on 2020-08-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200828_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mv_product_kh1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mv_product_kh2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mv_product_kh3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mv_product_khd1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mv_product_khd2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mv_product_khd3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mv_product_khd4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mv_product_khd5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mv_product_khd6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mv_product_khd7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mv_product_khd8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mv_product_khd9',
        ),
    ]
