# Generated by Django 3.0.5 on 2020-08-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200828_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Rating',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_fname', models.CharField(max_length=50)),
                ('cust_lname', models.CharField(max_length=50)),
                ('cust_email', models.CharField(max_length=150)),
                ('rating', models.IntegerField(default='')),
            ],
        ),
    ]
