# Generated by Django 3.0.5 on 2020-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
