# Generated by Django 3.0.5 on 2020-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200831_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='product_rating',
            name='review',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
