# Generated by Django 3.0.5 on 2020-08-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200831_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_rating',
            name='prod_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
