# Generated by Django 3.0.5 on 2020-09-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_product_rating_prod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_rating',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
